dot:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 150

    left_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_left_joint
        pid: {p: 0.001, i: 0.0, d: 0.0001}

    back_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_back_joint
        pid: {p: 0.001, i: 0.0, d: 0.0001}

    right_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_right_joint
        pid: {p: 0.001, i: 0.0, d: 0.0001}