dot:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 150

    left_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_left_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

    back_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_back_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

    right_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_right_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
