dot:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    left_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_left_joint
        pid: {p: 0.01, i: 0.0, d: 0.0}

    back_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_back_joint
        pid: {p: 0.01, i: 0.0, d: 0.0}

    right_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: rim_right_joint
        pid: {p: 0.01, i: 0.0, d: 0.0}

    Xaxis_pos_controller:
        type: effort_controllers/JointPositionController
        joint: rev_x
        pid: { p: 100.0, i: 0.01, d: 0.0 }

    Yaxis_pos_controller:
        type: effort_controllers/JointPositionController
        joint: rev_y
        pid: { p: 100.0, i: 0.01, d: 0.0 }
