global_costmap:
  global_frame: map
  rolling_window: true
  track_unknown_space: true
  robot_base_frame: origin_link
  width: 5.0
  height: 5.0
  resolution: 0.05
  update_frequency: 20.0
  publish_frequency: 1.0
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
