local_costmap:
  global_frame: map
  robot_base_frame: origin_link
  update_frequency: 20.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 0.5
  height: 0.5
  resolution: 0.05
  transform_tolerance: 1.0
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
